name: NTC devops for flask
on: push

jobs:
  push-job:
    name: David
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: dependency
      run: |
        pip3 install -r requirements.txt
    - name: Run server 
      run: |                 
